/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoomIndexImport } from './routes/room/$index'
import { Route as JoinIndexImport } from './routes/_join/index'

// Create/Update Routes

const RoomIndexRoute = RoomIndexImport.update({
  id: '/room/$index',
  path: '/room/$index',
  getParentRoute: () => rootRoute,
} as any)

const JoinIndexRoute = JoinIndexImport.update({
  id: '/_join/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/room/$index': {
      id: '/room/$index'
      path: '/room/$index'
      fullPath: '/room/$index'
      preLoaderRoute: typeof RoomIndexImport
      parentRoute: typeof rootRoute
    }
    '/_join/': {
      id: '/_join/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof JoinIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/room/$index': typeof RoomIndexRoute
  '/': typeof JoinIndexRoute
}

export interface FileRoutesByTo {
  '/room/$index': typeof RoomIndexRoute
  '/': typeof JoinIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/room/$index': typeof RoomIndexRoute
  '/_join/': typeof JoinIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/room/$index' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/room/$index' | '/'
  id: '__root__' | '/room/$index' | '/_join/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RoomIndexRoute: typeof RoomIndexRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RoomIndexRoute: RoomIndexRoute,
  JoinIndexRoute: JoinIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/room/$index",
        "/_join/"
      ]
    },
    "/room/$index": {
      "filePath": "room/$index.tsx"
    },
    "/_join/": {
      "filePath": "_join/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
